[project]
name = "alpha-zero-chess"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chess>=1.11.2",
    "numpy>=2.3.5",
    "pre-commit>=4.5.0",
    "ruff>=0.14.7",
    "torch>=2.9.1",
]
